include:
  - my-airflow/docker-compose.yaml
services:
  spark-master:
    profiles: [ "notebook", "cluster" ]
    build:
      context: .
      dockerfile: my-spark/Dockerfile
    image: my-spark:3.5.5
    environment:
      - SPARK_VERSION=3.5.5
    entrypoint: [ './entrypoint.sh', 'master' ]
    networks:
      - airflow-spark
    volumes:
      - spark-logs:/opt/spark/spark-events
      - ./data:/app/data
      - ./notebooks:/app/notebooks
    ports:
      - '8080:8080'
      - '7077:7077'
      - '8888:8888'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3

  spark-worker:
    profiles: [ "notebook", "cluster" ]
    build:
      context: .
      dockerfile: my-spark/Dockerfile
    image: my-spark:3.5.5
    environment:
      - SPARK_VERSION=3.5.5
    entrypoint: [ './entrypoint.sh', 'worker' ]
    networks:
      - airflow-spark
    volumes:
      - spark-logs:/opt/spark/spark-events
    depends_on:
      spark-master:
        condition: service_healthy

  s3:
    profiles: [ "cluster", "storage" ]
    build:
      context: .
      dockerfile: my-s3/Dockerfile
    image: my-s3:2.2.0
    environment:
      - RUST_LOG=garage=info
    networks:
      - airflow-spark
    volumes:
      - garage_meta:/var/lib/garage/meta
      - garage_data:/var/lib/garage/data
    ports:
      - '3900:3900'
      - '3901:3901'
      - '3902:3902'
      - '3903:3903'

networks:
  airflow-spark:
    driver: bridge

volumes:
  spark-logs:
  garage_meta:
  garage_data:
